spring:
  application:
    name: auth-app-practice

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_app_prac
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    # We can remove this line and let Spring detect it.
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # It automatically configures 'hibernate.hbm2ddl.auto' for you.
    hibernate:
      ddl-auto: update

    # 3. Logging: Good for debugging
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG


application:
  security:
    jwt:
      # This looks for a hidden environment variable. If it can't find one (like on your local laptop), it uses the default value after the colon.
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000
