spring:
  application:
    name: auth-app-practice

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_app_prac
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    # We can remove this line and let Spring detect it.
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # It automatically configures 'hibernate.hbm2ddl.auto' for you.
    hibernate:
      ddl-auto: update

    # 3. Logging: Good for debugging
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
